const vocabulary = {
    classroom: [
        { spanish: "Abran su libro", english: "Open your book" },
        { spanish: "Borren la pizarra", english: "Erase the board" },
        { spanish: "Busquen un compañero", english: "Look for a partner" },
        { spanish: "Cállense", english: "Be quiet" },
        { spanish: "Cambien papeles", english: "Trade/exchange papers" },
        { spanish: "Contesten", english: "Answer" },
        { spanish: "Corrijan los errores", english: "Correct the errors" },
        { spanish: "Entreguen la tarea", english: "Turn in homework" },
        { spanish: "Escuchen", english: "Listen" },
        { spanish: "Escojan un compañero", english: "Choose a partner" },
        { spanish: "Escriban", english: "Write" },
        { spanish: "Hablen", english: "Talk" },
        { spanish: "Hagan la tarea", english: "Do the homework" },
        { spanish: "Hagan una pregunta", english: "Ask a question" },
        { spanish: "Lean", english: "Read" },
        { spanish: "Lean en voz alta", english: "Read out loud" },
        { spanish: "Levántense", english: "Stand up" },
        { spanish: "Levanten la mano", english: "Raise your hand" },
        { spanish: "Miren la pizarra", english: "Look at the board" },
        { spanish: "Pasen a la pizarra", english: "Go to the board" },
        { spanish: "Pónganse en grupos", english: "Get into groups" },
        { spanish: "Presten atención", english: "Pay attention" },
        { spanish: "Regresen a su asiento", english: "Return to your seat" },
        { spanish: "Repita", english: "repeat" },
        { spanish: "Saquen papel", english: "Get out a sheet of paper" },
        { spanish: "Siéntense", english: "Sit down" },
        { spanish: "Siéntense en otra silla", english: "Sit in another seat" },
        { spanish: "Traduzcan al inglés", english: "Translate into English" },
        { spanish: "Traten de pronunciar", english: "Try to pronounce" },
        { spanish: "Vayan a la pizarra", english: "Go to the board" }
    ],
    greetings: [
        { spanish: "Adiós", english: "goodbye" },
        { spanish: "Buenas noches", english: "good evening" },
        { spanish: "Buenas tardes", english: "good afternoon" },
        { spanish: "Buenos días", english: "good morning" },
        { spanish: "Hasta luego", english: "see you later" },
        { spanish: "Hasta mañana", english: "see you tomorrow" },
        { spanish: "Hola", english: "hello" },
        { spanish: "Igualmente", english: "likewise" },
        { spanish: "Mucho gusto", english: "pleased to meet you" },
        { spanish: "Nos vemos", english: "see you" }
    ],
    questions: [
        { spanish: "Cuántos/as", english: "how many" },
        { spanish: "Hay preguntas", english: "are there any questions" },
        { spanish: "Hay que", english: "do we have to" },
        { spanish: "Puedo ir al baño", english: "may I go to the bathroom" },
        { spanish: "Qué día es hoy", english: "what day is today" },
        { spanish: "Qué página", english: "what page" },
        { spanish: "Qué pasa", english: "what's happening" },
        { spanish: "Qué significa", english: "what does it mean" },
        { spanish: "Qué tal", english: "how are you" },
        { spanish: "Qué tiempo hace", english: "what's the weather like" }
    ],
    days: [
        { spanish: "Lunes", english: "Monday" },
        { spanish: "Martes", english: "Tuesday" },
        { spanish: "Miércoles", english: "Wednesday" },
        { spanish: "Jueves", english: "Thursday" },
        { spanish: "Viernes", english: "Friday" },
        { spanish: "Sábado", english: "Saturday" },
        { spanish: "Domingo", english: "Sunday" }
    ],
    months: [
        { spanish: "Enero", english: "January" },
        { spanish: "Febrero", english: "February" },
        { spanish: "Marzo", english: "March" },
        { spanish: "Abril", english: "April" },
        { spanish: "Mayo", english: "May" },
        { spanish: "Junio", english: "June" },
        { spanish: "Julio", english: "July" },
        { spanish: "Agosto", english: "August" },
        { spanish: "Septiembre", english: "September" },
        { spanish: "Octubre", english: "October" },
        { spanish: "Noviembre", english: "November" },
        { spanish: "Diciembre", english: "December" }
    ],
    numbers: [
        { spanish: "Cero", english: "0" },
        { spanish: "Uno", english: "1" },
        { spanish: "Dos", english: "2" },
        { spanish: "Tres", english: "3" },
        { spanish: "Cuatro", english: "4" },
        { spanish: "Cinco", english: "5" },
        { spanish: "Seis", english: "6" },
        { spanish: "Siete", english: "7" },
        { spanish: "Ocho", english: "8" },
        { spanish: "Nueve", english: "9" },
        { spanish: "Diez", english: "10" },
        { spanish: "Once", english: "11" },
        { spanish: "Doce", english: "12" },
        { spanish: "Trece", english: "13" },
        { spanish: "Catorce", english: "14" },
        { spanish: "Quince", english: "15" },
        { spanish: "Dieciséis", english: "16" },
        { spanish: "Diecisiete", english: "17" },
        { spanish: "Dieciocho", english: "18" },
        { spanish: "Diecinueve", english: "19" },
        { spanish: "Veinte", english: "20" },
        { spanish: "Veintiuno", english: "21" },
        { spanish: "Veintidós", english: "22" },
        { spanish: "Veintitrés", english: "23" },
        { spanish: "Veinticuatro", english: "24" },
        { spanish: "Veinticinco", english: "25" },
        { spanish: "Veintiséis", english: "26" },
        { spanish: "Veintisiete", english: "27" },
        { spanish: "Veintiocho", english: "28" },
        { spanish: "Veintinueve", english: "29" },
        { spanish: "Treinta", english: "30" },
        { spanish: "Cuarenta", english: "40" },
        { spanish: "Cincuenta", english: "50" },
        { spanish: "Sesenta", english: "60" },
        { spanish: "Setenta", english: "70" },
        { spanish: "Ochenta", english: "80" },
        { spanish: "Noventa", english: "90" },
        { spanish: "Cien", english: "100" }
    ],
    pronouns: [
        { spanish: "Yo", english: "I" },
        { spanish: "Tú", english: "you (informal)" },
        { spanish: "Él", english: "he" },
        { spanish: "Ella", english: "she" },
        { spanish: "Usted", english: "you (formal)" },
        { spanish: "Nosotros", english: "we" },
        { spanish: "Vosotros", english: "y'all (informal, Spain)" },
        { spanish: "Ellos", english: "they" },
        { spanish: "Ellas", english: "they (all female)" },
        { spanish: "Ustedes", english: "y'all (formal/informal)" }
    ],
    seasons: [
        { spanish: "Primavera", english: "spring" },
        { spanish: "Verano", english: "summer" },
        { spanish: "Otoño", english: "fall/autumn" },
        { spanish: "Invierno", english: "winter" }
    ],
    time: [
        { spanish: "Y cuarto", english: "quarter past" },
        { spanish: "Y media", english: "half past" },
        { spanish: "Menos cuarto", english: "quarter to" }
    ],
    weather: [
        { spanish: "Hace calor", english: "it's hot" },
        { spanish: "Hace frío", english: "it's cold" },
        { spanish: "Hace sol", english: "it's sunny" },
        { spanish: "Hace viento", english: "it's windy" },
        { spanish: "Llueve", english: "it's raining" },
        { spanish: "Nieva", english: "it's snowing" }
    ]
}; 